name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker image
      run: | 
        echo "${{secrets.PASSWORD}}" | docker login -u "suhail12" --password-stdin
        docker image build -t suhail12/mytodoapp:stable-latest .
        docker tag suhail12/mytodoapp:stable-latest suhail12/mytodoapp:stable-${GITHUB_REF/refs\/tags\//}
        docker tag suhail12/mytodoapp:stable-latest suhail12/mytodoapp:stable-${GITHUB_SHA::8}
        docker push suhail12/mytodoapp:stable-latest
        docker push suhail12/mytodoapp:stable-${GITHUB_REF/refs\/tags\//}
        docker push suhail12/mytodoapp:stable-${GITHUB_SHA::8}
