name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
    - run: | 
        echo "${{secrets.PASSWORD}}" | docker login -u "suhail12" --password --password-stdin
        docker image build -t suhail12/mytodoapp:(date %s} .
        docker push suhail12/mytodoapp:(date %s}
